export type QueryState = 'IDLE' | 'LISTENING' | 'TRANSCRIBING' | 'QUERY_SCORING' | 'RETRIEVING' | 'CHUNK_SCORING' | 'GENERATING' | 'VALIDATING' | 'REDACTING' | 'COMPLETE' | 'BLOCKED' | 'REFUSED' | 'ERROR'
export type Decision = 'ALLOW' | 'REVIEW' | 'BLOCK' | 'QUARANTINE' | string
export interface QuerySecurity { risk_score: number; decision: Decision; label?: string; model?: string; latency_ms?: number }
export interface Retrieval { candidate_count: number; quarantined_count: number; safe_count: number; latency_ms?: number }
export interface Evidence { email_id: string; chunk_id: string; parent_id?: string | null; section?: string | null; title?: string | null; preview: string; decision: Decision; injection_score?: number | null; boundary_reason?: string | null; char_count?: number | null; token_estimate?: number | null; quarantined?: boolean }
export interface PipelineStage { id: string; label: string; state: string; duration_ms?: number | null; risk?: number | null; count_label?: string | null }
export interface QueryResponse { request_id: string; status: 'ok' | 'blocked' | 'refused' | 'error'; transcript?: string | null; query_security?: QuerySecurity | null; retrieval?: Retrieval | null; answer?: string | null; citations: { email_id: string; chunk_id: string }[]; privacy?: { pii_detected: boolean; redaction_count: number; pii_redacted?: boolean | null; sanitized_text: string } | null; evidence: Evidence[]; pipeline: PipelineStage[]; reason?: string | null; risk_score?: number | null; llm_called: boolean; grounded?: boolean | null; source?: string | null; trace?: Record<string, unknown> }
export interface Health { status: string; app: string; corpus_emails: number; source_emails: number; indexed_email_count: number; chunk_count: number; index_status: string; index_ready: boolean; classifier_ready: boolean; llm_ready: boolean; embedding_ready: boolean; dataset: ComponentStatus; embedding: ComponentStatus; classifier: ComponentStatus; llm: ComponentStatus; retrieval: ComponentStatus; voice: ComponentStatus; privacy: ComponentStatus }
export interface ComponentStatus { status: string; detail?: string | null; emails?: number | null; model?: string | null }
export interface ChunkDetail { chunk_id: string; email_id: string; parent_id?: string | null; section?: string | null; boundary_reason?: string | null; char_count?: number | null; token_estimate?: number | null; injection_score?: number | null; decision?: string | null; preview: string; metadata: Record<string, unknown> }
export interface Score { risk_score: number; decision: Decision; label?: string; model?: string }
