import { useCallback, useEffect, useMemo, useState } from 'react'
import { api } from './api/client'
import { Evidence } from './components/Evidence'
import { Inspector } from './components/Inspector'
import { Pipeline } from './components/Pipeline'
import { useVoice } from './hooks/useVoice'
import { formatScore, labelFor, stateLabel, statusClass } from './lib/format'
import type { Evidence as EvidenceItem, Health, QueryResponse, QueryState, Score } from './types/api'

type Nav = 'Search' | 'Evidence' | 'Security' | 'Inspect'

function App() {
  const [state, setState] = useState<QueryState>('IDLE'); const [query, setQuery] = useState(''); const [result, setResult] = useState<QueryResponse | null>(null)
  const [score, setScore] = useState<Score | null>(null); const [health, setHealth] = useState<Health | null>(null); const [healthError, setHealthError] = useState(''); const [error, setError] = useState('')
  const [inspected, setInspected] = useState<EvidenceItem | null>(null); const [nav, setNav] = useState<Nav>('Search'); const [busy, setBusy] = useState(false)
  const [typedSource, setTypedSource] = useState<'voice' | 'typed'>('typed')
  useEffect(() => { let live = true; const refresh = () => api.health().then(data => { if (live) { setHealth(data); setHealthError('') } }).catch(e => { if (live) setHealthError(e instanceof Error ? e.message : 'Health service unavailable.') }); refresh(); const timer = window.setInterval(refresh, 30000); return () => { live = false; window.clearInterval(timer) } }, [])
  useEffect(() => { const handler = (event: Event) => { setError((event as CustomEvent<string>).detail); setState('ERROR') }; window.addEventListener('riptide-error', handler); return () => window.removeEventListener('riptide-error', handler) }, [])
  const submit = useCallback(async (text = query, source: 'typed' | 'voice' = typedSource) => {
    const clean = text.trim(); if (!clean || busy) return
    setQuery(clean); setBusy(true); setError(''); setResult(null); setScore(null); setState('QUERY_SCORING')
    try {
      try { const value = await api.score(clean); setScore(value); if (/block/i.test(value.decision)) { setState('BLOCKED') } }
      catch { /* The pipeline endpoint remains authoritative and fails closed. */ }
      setState(current => current === 'BLOCKED' ? current : 'RETRIEVING')
      const response = await api.query(clean, source); setResult(response)
      if (response.status === 'blocked') setState('BLOCKED')
      else if (response.status === 'refused') setState('REFUSED')
      else if (response.status === 'error') setState('ERROR')
      else {
        if (response.retrieval) setState('CHUNK_SCORING')
        if (response.answer) setState('GENERATING')
        if (response.privacy?.pii_detected) setState('REDACTING')
        setState('COMPLETE')
      }
      if (response.transcript) setQuery(response.transcript)
    } catch (e) { setError(e instanceof Error ? e.message : 'The query service is unavailable.'); setState('ERROR') }
    finally { setBusy(false) }
  }, [query, busy, typedSource])
  const voiceState = useCallback((next: 'LISTENING' | 'TRANSCRIBING' | 'ERROR') => { if (next !== 'ERROR') { setState(next); setError('') } }, [])
  const onTranscript = (text: string) => { setQuery(text); setTypedSource('voice'); setState('IDLE'); void submit(text, 'voice') }
  const { start: startVoice, stop: stopVoice, seconds } = useVoice(onTranscript, voiceState)
  const evidence = result?.evidence || []
  const pipeline = useMemo(() => result?.pipeline || [], [result])
  const navItems: Nav[] = ['Search', 'Evidence', 'Security', 'Inspect']
  const scrollTo = (item: Nav) => { setNav(item); const id = item === 'Search' ? 'search' : item === 'Evidence' ? 'evidence' : item === 'Security' ? 'security' : 'inspect-target'; document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: item === 'Inspect' ? 'nearest' : 'start' }); if (item === 'Inspect' && evidence[0]) setInspected(evidence[0]) }
  const serviceReady = Boolean(health?.index_ready && health?.classifier_ready && health?.llm_ready)
  const hasIncident = state === 'BLOCKED' || result?.status === 'blocked'

  return <div className="app-shell"><aside className="rail"><a href="#search" className="brand" aria-label="Riptide home"><span className="brand-mark">R</span><span>RIPTIDE<small>SECURITY OPERATIONS</small></span></a><div className="rail-caption">WORKSPACE</div><nav aria-label="Workspace navigation">{navItems.map((item, i) => <button key={item} onClick={() => scrollTo(item)} className={`nav-item ${nav === item ? 'selected' : ''}`}><span className="nav-symbol" aria-hidden="true">{['⌕', '▤', '⛨', '⊞'][i]}</span>{item}</button>)}</nav><div className="rail-bottom"><div className="health-mini"><span className={`health-dot ${serviceReady ? 'online' : 'offline'}`} /><div><strong>{healthError ? 'API UNAVAILABLE' : serviceReady ? 'SYSTEM READY' : 'SYSTEM STATUS'}</strong><small>{health?.corpus_emails != null ? `${health.corpus_emails.toLocaleString()} source emails` : 'Awaiting health check'}</small></div></div><span className="build-label">RIPTIDE / ZERO TRUST</span></div></aside>
    <main className="workspace"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> Search</div><div className="top-status"><span className={`status ${healthError ? 'danger' : serviceReady ? 'safe' : 'caution'}`}><i />{healthError ? 'API UNAVAILABLE' : serviceReady ? 'ZERO TRUST ACTIVE' : health ? 'PARTIAL READINESS' : 'CONNECTING'}</span><button className="health-button" onClick={() => api.health().then(setHealth).catch(e => setHealthError(e instanceof Error ? e.message : 'Health service unavailable.'))} aria-label="Refresh system health">↻</button></div></header>
      <div className="content"><section className="command-area" id="search"><div className="page-intro"><div><span className="eyebrow">SECURE ARCHIVE SEARCH</span><h1>Ask the archive</h1><p>Search trusted evidence by voice or text. Every input and source is checked.</p></div><div className="session-card"><span className="session-icon">⛨</span><div><span className="eyebrow">SESSION POSTURE</span><strong>{health?.status?.toUpperCase() || 'CHECKING'}</strong></div></div></div>
        <div className="query-panel"><div className="voice-row"><button className={`voice-button ${state === 'LISTENING' ? 'recording' : ''}`} onClick={() => state === 'LISTENING' ? stopVoice() : void startVoice()} disabled={busy && state !== 'LISTENING'}><span className="mic-symbol" aria-hidden="true">{state === 'LISTENING' ? '■' : '◖'}</span><span>{state === 'LISTENING' ? `Stop recording · 00:${String(seconds).padStart(2, '0')}` : state === 'TRANSCRIBING' ? 'Transcribing audio…' : 'Speak a query'}</span><span className="voice-hint">{state === 'LISTENING' ? 'STOP' : 'WHISPER'}</span></button><div className="voice-note"><span className="record-dot" /> Browser audio is sent to the configured Whisper service</div></div><div className="or-divider"><span>OR ENTER A QUERY</span></div><form className="typed-form" onSubmit={event => { event.preventDefault(); setTypedSource('typed'); void submit(query, 'typed') }}><label htmlFor="query-input" className="sr-only">Search the archive</label><textarea id="query-input" rows={2} value={query} onChange={event => { setQuery(event.target.value); if (state === 'ERROR' || state === 'BLOCKED' || state === 'COMPLETE') setState('IDLE') }} placeholder="What decisions were discussed in the contract negotiations?" onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); setTypedSource('typed'); void submit(query, 'typed') } }} /><button className="button primary submit-button" disabled={busy || !query.trim()}>{busy ? <><span className="spinner" /> Processing</> : 'Run secure search'}</button></form><div className="query-footer"><span>Enter to search <kbd>↵</kbd> <span className="footer-separator">·</span> Shift + Enter for a new line</span><span>Query Guard runs before generation</span></div></div>
        <div className={`current-state ${statusClass(state)}`} role="status" aria-live="polite"><span className="state-indicator"><i /></span><strong>{stateLabel[state]}</strong>{score && <span className="state-detail">Query risk <b className="mono">{formatScore(score.risk_score)}</b> · {labelFor(score.decision)}</span>}{result?.request_id && <code className="request-id">{result.request_id}</code>}</div>
        {error && <div className="error-banner" role="alert"><strong>Request could not complete</strong><span>{error}</span><button className="text-button" onClick={() => { setError(''); setState('IDLE') }}>Dismiss</button></div>}
      </section>

      <section id="security"><Pipeline state={state} data={pipeline} /></section>
      {hasIncident && <section className="incident" role="alert"><div className="incident-title"><span className="incident-mark">!</span><div><span className="eyebrow">SECURITY DECISION</span><h2>Query blocked</h2></div></div><p>Injection risk detected. The query was denied by the security policy.</p><div className="incident-facts"><div><span>Risk score</span><strong className="mono">{formatScore(result?.risk_score ?? score?.risk_score)}</strong></div><div><span>Policy decision</span><strong>BLOCK</strong></div><div><span>LLM call</span><strong>{result?.llm_called ? 'EXECUTED' : 'NOT EXECUTED'}</strong></div></div><details><summary>View detection details</summary><p>{result?.reason || score?.label || 'The query guard returned a block decision.'}</p></details></section>}
      {state === 'REFUSED' && <section className="refusal" role="status"><span className="eyebrow">SAFE REFUSAL</span><h2>Evidence was not sufficient</h2><p>{result?.reason || 'No supported answer could be produced from safe evidence.'}</p></section>}
      <div className="results-grid"><div className="primary-column"><section className="panel answer-panel"><div className="section-heading"><div><span className="eyebrow">OUTPUT GATE</span><h2>Answer</h2></div>{result?.privacy?.pii_redacted && <span className="status safe"><i />REDACTED</span>}</div>{result?.answer ? <><div className="answer-meta"><span className={`status ${result.grounded === false ? 'caution' : 'safe'}`}><i />{result.grounded === false ? 'GROUNDING UNCONFIRMED' : 'GROUNDED'}</span><span>{result.citations.length} {result.citations.length === 1 ? 'SOURCE' : 'SOURCES'}</span>{result.privacy?.pii_redacted && <span className="privacy-tag">PII FILTERED · {result.privacy.redaction_count} REDACTIONS</span>}</div><p className="answer-copy">{result.privacy?.sanitized_text || result.answer}</p><div className="answer-footer"><span><i className="safe-dot" />{result.privacy?.pii_redacted ? 'Privacy gate passed · sensitive data removed' : 'Output received from the configured generation service'}</span><code>{result.request_id}</code></div></> : <div className="empty-state answer-empty">{state === 'IDLE' ? 'A verified answer will appear here after a search.' : state === 'BLOCKED' ? 'Generation was stopped by the query security gate.' : state === 'REFUSED' ? 'The system declined to answer without sufficient safe evidence.' : state === 'ERROR' ? 'No answer was returned because a required service failed.' : 'Answer content is not yet available from the API.'}</div>}</section>
        <div id="evidence"><Evidence items={evidence} onInspect={item => { setInspected(item); setNav('Inspect') }} /></div></div>
        <aside className="side-column"><section className="panel query-check"><div className="section-heading"><div><span className="eyebrow">INPUT SECURITY</span><h2>Query guard</h2></div><span className={`status ${statusClass(score?.decision)}`}><i />{labelFor(score?.decision)}</span></div><div className="risk-readout"><span>Injection risk score</span><strong className="mono">{formatScore(score?.risk_score ?? result?.query_security?.risk_score)}</strong></div><div className="risk-track"><span className={statusClass(score?.decision)} style={{ width: `${Math.max(0, Math.min(100, (score?.risk_score ?? result?.query_security?.risk_score ?? 0) * 100))}%` }} /></div><div className="diagnostic-lines"><div><span>Decision model</span><code>{score?.model || result?.query_security?.model || 'Not reported'}</code></div><div><span>Score latency</span><code>{result?.query_security?.latency_ms != null ? `${result.query_security.latency_ms} ms` : 'Not reported'}</code></div></div></section>
          <section className="panel retrieval-card"><div className="section-heading"><div><span className="eyebrow">RETRIEVAL</span><h2>Evidence review</h2></div><span className="retrieval-mark">↳</span></div><div className="retrieval-numbers"><div><strong>{result?.retrieval?.candidate_count ?? '—'}</strong><span>Candidates</span></div><div><strong className="safe-text">{result?.retrieval?.safe_count ?? '—'}</strong><span>Safe</span></div><div><strong className="danger-text">{result?.retrieval?.quarantined_count ?? '—'}</strong><span>Quarantined</span></div></div><div className="review-note">{result?.retrieval ? `${result.retrieval.latency_ms != null ? `${result.retrieval.latency_ms} ms` : 'Latency not reported'} · unsafe chunks excluded from generation` : 'Counts are provided by the retrieval service after a query.'}</div></section>
          <section className="panel system-card"><div className="section-heading"><div><span className="eyebrow">SERVICE STATUS</span><h2>System health</h2></div><button className="icon-button small" onClick={() => api.health().then(setHealth).catch(e => setHealthError(e instanceof Error ? e.message : 'Health check failed.'))} aria-label="Refresh health">↻</button></div>{healthError ? <div className="health-error">Health endpoint unavailable: {healthError}</div> : !health ? <div className="empty-state">Connecting to health endpoint…</div> : <><div className="corpus-summary"><span>Source emails</span><strong>{health.source_emails.toLocaleString()}</strong></div><div className="diagnostic-lines"><div><span>Indexed emails</span><code>{health.indexed_email_count.toLocaleString()}</code></div><div><span>Chunks / index</span><code>{health.chunk_count.toLocaleString()} · {health.index_status}</code></div></div><div className="service-list">{[['Dataset', health.dataset.status], ['Index', health.index_ready ? 'Ready' : 'Unavailable'], ['Classifier', health.classifier.status], ['Embedding', health.embedding.status], ['Generation', health.llm.status], ['Whisper', health.voice.status], ['Privacy', health.privacy.status]].map(([name, value]) => <div className="service-row" key={name}><span><i className={`service-dot ${statusClass(value)}`} />{name}</span><code>{value}</code></div>)}</div></>}</section></aside></div>
      <footer className="page-footer"><span>RIPTIDE SECURITY OPERATIONS CONSOLE</span><span>Evidence is data. Every boundary is checked.</span></footer>
      </div></main><Inspector item={inspected} onClose={() => setInspected(null)} /></div>
}

export default App
